import type { Metadata } from "next";
import { robotoMono } from "./ui/fonts";
import Providers from './ui/provider'
import "./globals.css";
import "./animate.css"

export const metadata: Metadata = {
  title: "Eventer App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="format-detection"
          content="telephone=no, date=no, email=no, address=no"
        />
      </head>
      <body className={robotoMono.className} suppressHydrationWarning><Providers>{children}</Providers></body>
    </html>
  );
}
