import type { Metadata } from "next";
import { robotoMono } from "./ui/fonts";
import "./globals.css";
import "./animate.css"

export const metadata: Metadata = {
  title: "Eventer App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoMono.className}>{children}</body>
    </html>
  );
}
